[package]
name = "oxcable"
version = "0.1.0"
authors = ["Michael Nye <thenyeguy@gmail.com>"]
license = "Creative Commons BY-NC-SA 4.0"
repository = "https://github.com/thenyeguy/OxilaryCable"
description = "A simple audio processing and MIDI framework in Rust."

[lib]
name = "oxcable"
path = "src/oxcable.rs"

[dependencies]
rand = "0.1.2"
portmidi = "0.0.4"

[dependencies.rust-portaudio]
git = "https://github.com/mitchmindtree/rust-portaudio.git"
