[package]
name = "OxilaryCable"
version = "0.0.1"
authors = ["Michael Nye <thenyeguy@gmail.com>"]

[lib]
name = "oxcable"
path = "src/oxcable.rs"

[dependencies]
portaudio = "~0.3.0"

[dependencies.portmidi]
git = "https://github.com/musitdev/rust-portmidi.git"
